addSbtPlugin("org.foundweekends.giter8" %% "sbt-giter8" % "0.12.0")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.4.31")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.10")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.5.2")
